### ISSUE TITLE
修改博客主页面内容

### ISSUE THREAD

**Issue by cayzlh** [cayzlh/fluffy-guide#2]
简单记录一下修改过程：

1. 修改博客配置文件`_config.yml`中`index_generator`配置如下：

   ```yaml
   index_generator:
     path: /posts
   ```

2. 修改主题配置文件：

   ```yaml
   sidebar:
     menu:
       home: '[btn.home](/)' # 新增的
       post:  '[btn.blog](/posts/)' # 默认为 '[btn.blog](/)'
   ```

3. 在`source`文件夹下新建一个`index.md`文件， 文件内容与`about`页面类似即可
